//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeLocatorDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Path
    {
        public int ID { get; set; }
        public int From_X_Value { get; set; }
        public int From_Y_Value { get; set; }
        public int To_X_Value { get; set; }
        public int To_Y_Value { get; set; }
    }
}
